twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        trick_images_dir: '%app.public_trick_img_dir%'
        account_images_dir: '%app.public_account_img_dir%'
